#include "common.h"

struct unops_tests {
    template<typename T, size_t... I, size_t N = sizeof...(I)>
    __host__ __device__ void operator()(generator<T> gen, std::index_sequence<I...>) {
        T items[N] = {gen.next(I)...};
        kf::vec<T, N> a = {items[I]...};
        kf::vec<T, N> b;

        b = -a;
        ASSERT_EQ_ALL(b[I], T(-items[I]));

        b = ~a;
        ASSERT_EQ_ALL(b[I], T(~items[I]));

        b = !a;
        ASSERT_EQ_ALL(b[I], T(!items[I]));
    }
};

REGISTER_TEST_CASE("unary operators", unops_tests, bool, int)

struct unops_float_tests {
    template<typename T, size_t... I, size_t N = sizeof...(I)>
    __host__ __device__ void operator()(generator<T> gen, std::index_sequence<I...>) {
        double items[N] = {gen.next(I)...};
        kf::vec<T, N> a = {T(items[I])...};
        kf::vec<T, N> b;

        b = -a;
        ASSERT_EQ_ALL(b[I], T(-items[I]));

        b = !a;
        ASSERT_EQ_ALL(b[I], items[I] == 0.0 ? T(1.0) : T(0.0));

        // Ideally, we would test all unary operators, but that would be a lot of work and not that useful since
        // all operators are generated by the same macro. Instead, we only check a few of them
        if constexpr (is_one_of<T, __half, __nv_bfloat16>) {
            // operations on 16-bit numbers are only supported in CC >= 8
#if KERNEL_FLOAT_CUDA_ARCH >= 800
            b = sqrt(a);
            ASSERT_EQ_ALL(b[I], hsqrt(T(items[I])));

            b = sin(a);
            ASSERT_EQ_ALL(b[I], hsin(T(items[I])));

            b = cos(a);
            ASSERT_EQ_ALL(b[I], hcos(T(items[I])));

            b = log(a);
            ASSERT_EQ_ALL(b[I], hlog(T(items[I])));

            b = exp(a);
            ASSERT_EQ_ALL(b[I], hexp(T(items[I])));

            b = rcp(a);
            ASSERT_EQ_ALL(b[I], hrcp(T(items[I])));

            b = rsqrt(a);
            ASSERT_EQ_ALL(b[I], hrsqrt(T(items[I])));
#endif
        } else {
            b = sqrt(a);
            ASSERT_EQ_ALL(b[I], sqrt(T(items[I])));

            b = sin(a);
            ASSERT_EQ_ALL(b[I], sin(T(items[I])));

            b = cos(a);
            ASSERT_EQ_ALL(b[I], cos(T(items[I])));

            b = log(a);
            ASSERT_EQ_ALL(b[I], log(T(items[I])));

            b = exp(a);
            ASSERT_EQ_ALL(b[I], exp(T(items[I])));

            b = rcp(a);
            ASSERT_EQ_ALL(b[I], T(1.0 / items[I]));

            // seems that rsqrt does not match bitwise on GPU
            b = rsqrt(a);
            ASSERT_APPROX_ALL(b[I], rsqrt(T(items[I])));
        }
    }
};

REGISTER_TEST_CASE("unary float operators", unops_float_tests, float, double)
REGISTER_TEST_CASE_GPU("unary float operators", unops_float_tests, __half, __nv_bfloat16)
