name: CMake

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-cuda:
    uses: ./.github/workflows/cmake-action.yml
    with:
      cuda-version: "12.8.0"

  build-cuda-12-6:
    needs: build-cuda
    uses: ./.github/workflows/cmake-action.yml
    with:
      cuda-version: "12.6.0"

  build-cuda-12-5:
    needs: build-cuda
    uses: ./.github/workflows/cmake-action.yml
    with:
      cuda-version: "12.5.0"
